/* Barkhaus — images.js
 * Path-based image references. Upload the /images/ folder to GitHub
 * alongside index.html and this file.
 */
const BARKHAUS_IMAGES = {

  hero: "images/hero-01.jpg",

  b1: [   // Estancia
    "images/estancia-01.jpg",
    "images/estancia-02.jpg",
    "images/estancia-03.jpg",
    "images/estancia-04.jpg",
    "images/estancia-05.jpg",
    "images/estancia-06.jpg",
    "images/estancia-07.jpg",
    "images/estancia-10.jpg",
    "images/estancia-11.jpg",
    "images/estancia-12.jpg",
    "images/estancia-13.jpg",
    "images/estancia-14.jpg",
    "images/estancia-15.jpg",
  ],

  b2: [   // Eastwood
    "images/eastwood-01.jpg",
    "images/eastwood-02.jpg",
    "images/eastwood-03.jpg",
    "images/eastwood-04.jpg",
    "images/eastwood-05.jpg",
    "images/eastwood-06.jpg",
    "images/eastwood-07.jpg",
    "images/eastwood-08.jpg",
    "images/eastwood-09.jpg",
    "images/eastwood-10.jpg",
    "images/eastwood-11.jpg",
    "images/eastwood-12.jpg",
    "images/eastwood-13.jpg",
    "images/eastwood-15.jpg",
  ],

  services: {
    playpark: [
      "images/playpark-01.jpg",
      "images/playpark-02.jpg",
      "images/playpark-03.jpg",
      "images/playpark-04.jpg",
      "images/playpark-05.jpg",
      "images/playpark-06.jpg",
      "images/playpark-07.jpg",
      "images/playpark-08.jpg",
      "images/playpark-09.jpg",
      "images/playpark-10.jpg",
      "images/playpark-11.jpg",
      "images/playpark-12.jpg",
      "images/playpark-13.jpg",
      "images/playpark-14.jpg",
      "images/playpark-15.jpg",
      "images/playpark-16.jpg",
      "images/playpark-17.jpg",
      "images/playpark-18.jpg",
      "images/playpark-19.jpg",
      "images/playpark-20.jpg",
    ],
    daycare: [
      "images/daycare-01.jpg",
      "images/daycare-02.jpg",
      "images/daycare-03.jpg",
      "images/daycare-04.jpg",
      "images/daycare-05.jpg",
      "images/daycare-06.jpg",
      "images/daycare-07.jpg",
      "images/daycare-08.jpg",
      "images/daycare-09.jpg",
      "images/daycare-10.jpg",
      "images/daycare-11.jpg",
      "images/daycare-12.jpg",
      "images/daycare-13.jpg",
      "images/daycare-14.jpg",
      "images/daycare-15.jpg",
      "images/daycare-16.jpg",
    ],
    hotel: [
      "images/hotel-01.jpg",
      "images/hotel-02.jpg",
      "images/hotel-03.jpg",
      "images/hotel-04.jpg",
      "images/hotel-05.jpg",
      "images/hotel-06.jpg",
      "images/hotel-07.jpg",
      "images/hotel-08.jpg",
      "images/hotel-09.jpg",
    ],
    grooming: [
      "images/grooming-01.jpg",
      "images/grooming-02.jpg",
      "images/grooming-03.jpg",
      "images/grooming-04.jpg",
      "images/grooming-05.jpg",
      "images/grooming-06.jpg",
      "images/grooming-07.jpg",
      "images/grooming-08.jpg",
      "images/grooming-09.jpg",
      "images/grooming-10.jpg",
      "images/grooming-11.jpg",
      "images/grooming-12.jpg",
    ],
    studio: [
      "images/studio-01.jpg",
      "images/studio-02.jpg",
      "images/studio-03.jpg",
      "images/studio-04.jpg",
      "images/studio-05.jpg",
      "images/studio-06.jpg",
      "images/studio-07.JPG",
      "images/studio-08.JPG",
      "images/studio-09.JPG",
      "images/studio-10.JPG",
      "images/studio-11.JPG",
      "images/studio-12.JPG",
      "images/studio-13.JPG",
      "images/studio-14.JPG",
      "images/studio-15.JPG",
      "images/studio-16.JPG",
      "images/studio-17.JPG",
    ],
    events: [
      "images/events-01.jpg",
      "images/events-02.jpg",
      "images/events-03.jpg",
      "images/events-04.jpg",
      "images/events-05.jpg",
      "images/events-06.jpg",
      "images/events-07.jpg",
      "images/events-08.jpg",
      "images/events-09.jpg",
      "images/events-10.jpg",
      "images/events-11.jpg",
      "images/events-12.jpg",
      "images/events-13.jpg",
      "images/events-14.jpg",
      "images/events-15.jpg",
      "images/events-16.jpg",
      "images/events-17.jpg",
    ],
    store: [
      "images/store-01.jpg",
      "images/store-02.jpg",
      "images/store-03.jpg",
      "images/store-04.jpg",
      "images/store-05.jpg",
      "images/store-06.jpg",
      "images/store-07.jpg",
      "images/store-08.jpg",
      "images/store-09.jpg",
      "images/store-10.jpg",
    ],
    cafe: [
      "images/cafe-01.jpg",
      "images/cafe-02.jpg",
      "images/cafe-03.jpg",
      "images/cafe-04.jpg",
      "images/cafe-05.jpg",
      "images/cafe-06.jpg",
    ],
  },

};

/* Refresh cached local photos when the bundled gallery is updated. */
const BARKHAUS_IMAGE_VERSION = "20260624-services";
BARKHAUS_IMAGES.hero += "?v=" + BARKHAUS_IMAGE_VERSION;
BARKHAUS_IMAGES.b1 = BARKHAUS_IMAGES.b1.map(src => src + "?v=" + BARKHAUS_IMAGE_VERSION);
BARKHAUS_IMAGES.b2 = BARKHAUS_IMAGES.b2.map(src => src + "?v=" + BARKHAUS_IMAGE_VERSION);
Object.keys(BARKHAUS_IMAGES.services).forEach(key => {
  BARKHAUS_IMAGES.services[key] = BARKHAUS_IMAGES.services[key].map(src => src + "?v=" + BARKHAUS_IMAGE_VERSION);
});
