-- Orders: one hosted checkout (one Maya payment) can now cover several bookings.
-- Decision: docs/decisions/2026-09-20-accounts-orders-release.md
--
-- Backward-compatible by construction (the current site keeps working with this applied):
--   * booking_orders is a new table; nothing reads it until the order-aware functions deploy.
--   * bookings.order_id and pending_bookings.order_ref are new, nullable, and default to NULL,
--     so every existing row and every write from today's functions stays valid.
--   * Refs: bookings.ref_number is always generated by the generate_ref_number() trigger
--     (BH- + 6 chars from the booking id). The order ref is the FIRST booking's generated ref,
--     so a 1-item order looks exactly like today's single booking. Other bookings in the order keep
--     their own generated refs. The trigger is not changed.
-- Safe to re-run.

create table if not exists public.booking_orders (
  id                      uuid primary key default gen_random_uuid(),
  order_ref               text not null unique,
  owner_id                uuid references public.owners(id),
  branch_id               uuid references public.branches(id),
  -- Same units as pending_bookings.amount / bookings.total (whole pesos).
  amount                  integer not null check (amount >= 0),
  convenience_fee         integer not null default 0 check (convenience_fee >= 0),
  item_count              smallint not null default 1 check (item_count >= 1),
  status                  text not null default 'pending'
                            check (status in ('pending', 'paid', 'cancelled')),
  payment_provider        text,
  gateway_checkout_id     text,
  gateway_payment_id      text,
  cancellation_token_hash text,
  expires_at              timestamptz not null default (now() + interval '2 hours'),
  paid_at                 timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

comment on table public.booking_orders is
  'One hosted checkout = one order = one Maya payment. Each item is an ordinary bookings row with order_id set. '
  'order_ref is the first booking''s ref (generated by the bookings trigger); other items keep their own refs.';
comment on column public.booking_orders.amount is
  'What the customer pays for the whole order (sum of the bookings'' totals, fee included once).';

create index if not exists booking_orders_gateway_checkout_idx on public.booking_orders (gateway_checkout_id);
create index if not exists booking_orders_gateway_payment_idx  on public.booking_orders (gateway_payment_id);
create index if not exists booking_orders_status_expires_idx   on public.booking_orders (status, expires_at);

alter table public.bookings
  add column if not exists order_id uuid references public.booking_orders(id) on delete set null;
create index if not exists bookings_order_id_idx on public.bookings (order_id);
comment on column public.bookings.order_id is
  'The order (hosted checkout) this booking was paid through. NULL for bookings created before orders existed, and for admin/walk-in bookings.';

alter table public.pending_bookings
  add column if not exists order_ref text;
create index if not exists pending_bookings_order_ref_idx on public.pending_bookings (order_ref);
comment on column public.pending_bookings.order_ref is
  'booking_orders.order_ref this hold belongs to. NULL for holds created before orders existed (legacy path).';

-- Access: admins may read orders (admin booking drawer). Edge functions use the service role.
-- No customer or anonymous access: payment state is only ever changed server-side.
alter table public.booking_orders enable row level security;
drop policy if exists "booking_orders readable by admins" on public.booking_orders;
create policy "booking_orders readable by admins" on public.booking_orders
  for select to authenticated using (public.is_admin());

revoke all on public.booking_orders from anon;

notify pgrst, 'reload schema';
